name: DDO
title: DDO | Dan Dev Online
description: Dan Archer's development blog and personal portfolio
tags:
  - development
  - software
  - architecture
  - design
  - coding
  - programming
  - danarcheronline
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Portfolio
    url: /category/portfolio/
email: danarcheronline@gmail.com
disqus_username: ""
